package com.rockstudios.domain;
// Generated Aug 19, 2016 1:16:32 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Batch generated by hbm2java
 */
@Entity
@Table(name = "batches", catalog = "rockstudios")
public class Batches implements java.io.Serializable {

	private String id;
	private String batchName;
	private String startTime;
	private String endTime;
	private String status;
	private String description;
	private Date createdDate;
	private Set<CourseBatch> courseBatches = new HashSet<CourseBatch>(0);

	public Batches() {
	}

	public Batches(String id, String batchName, String startTime, String endTime, String status, Date createdDate) {
		this.id = id;
		this.batchName = batchName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.status = status;
		this.createdDate = createdDate;
	}

	public Batches(String id, String batchName, String startTime, String endTime, String status, String description,
			Date createdDate, Set<CourseBatch> courseBatches) {
		this.id = id;
		this.batchName = batchName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.status = status;
		this.description = description;
		this.createdDate = createdDate;
		this.courseBatches = courseBatches;
	}


	@Column(name = "batch_name", nullable = false, length = 45)
	public String getBatchName() {
		return this.batchName;
	}

	public void setBatchName(String batchName) {
		this.batchName = batchName;
	}

	@Column(name = "start_time", nullable = false, length = 45)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time", nullable = false, length = 45)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "batches")
	public Set<CourseBatch> getCourseBatches() {
		return this.courseBatches;
	}

	public void setCourseBatches(Set<CourseBatch> courseBatches) {
		this.courseBatches = courseBatches;
	}

}
