package com.rockstudios.domain;
// Generated Aug 19, 2016 1:16:32 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseBatch generated by hbm2java
 */
@Entity
@Table(name = "course_batch", catalog = "rockstudios")
public class CourseBatch extends AbstractDomain implements java.io.Serializable {

	private Course course;
	private Batches batches;
	private String status;
	private String description;
	private Set<CourseProgramBatchStudent> courseProgramBatchStudents = new HashSet<CourseProgramBatchStudent>(0);

	public CourseBatch() {
	}

	public CourseBatch(String id, Course course, Batches batches, String status) {
		this.id = id;
		this.course = course;
		this.batches = batches;
		this.status = status;
	}

	public CourseBatch(String id, Course course, Batches batches, String status, String description,
			Set<CourseProgramBatchStudent> courseProgramBatchStudents) {
		this.id = id;
		this.course = course;
		this.batches = batches;
		this.status = status;
		this.description = description;
		this.courseProgramBatchStudents = courseProgramBatchStudents;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "batches_id", nullable = false)
	public Batches getBatches() {
		return this.batches;
	}

	public void setBatches(Batches batches) {
		this.batches = batches;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseBatch" , cascade = CascadeType.ALL)
	public Set<CourseProgramBatchStudent> getCourseProgramBatchStudents() {
		return this.courseProgramBatchStudents;
	}

	public void setCourseProgramBatchStudents(Set<CourseProgramBatchStudent> courseProgramBatchStudents) {
		this.courseProgramBatchStudents = courseProgramBatchStudents;
	}

}
