package com.rockstudios.domain;
// Generated Aug 19, 2016 1:16:32 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrganisationBranch generated by hbm2java
 */
@Entity
@Table(name = "organisation_branch", catalog = "rockstudios")
public class OrganisationBranch extends AbstractDomain implements java.io.Serializable {

	private Organisation organisation;
	private String branchName;
	private String branchEmailId;
	private String branchPhoneNo;
	private String branchAlternativePhoneNo;
	private String status;
	private String createdDate;
	private String branchCode;
	private Integer branchCount;
	private String address;
	private Set<Course> courses = new HashSet<Course>(0);

	public OrganisationBranch() {
	}

	public OrganisationBranch(String id, Organisation organisation, String branchName, String branchPhoneNo,
			String status, String createdDate, String branchCode, Integer branchCount) {
		this.id = id;
		this.organisation = organisation;
		this.branchName = branchName;
		this.branchPhoneNo = branchPhoneNo;
		this.status = status;
		this.createdDate = createdDate;
		this.branchCode = branchCode;
		this.branchCount = branchCount;
	}

	public OrganisationBranch(String id, Organisation organisation, String branchName, String branchEmailId,
			String branchPhoneNo, String branchAlternativePhoneNo, Integer branchCount, String status,
			String createdDate, String branchCode, Set<Course> courses) {
		this.id = id;
		this.organisation = organisation;
		this.branchName = branchName;
		this.branchEmailId = branchEmailId;
		this.branchPhoneNo = branchPhoneNo;
		this.branchAlternativePhoneNo = branchAlternativePhoneNo;
		this.status = status;
		this.createdDate = createdDate;
		this.branchCode = branchCode;
		this.branchCount = branchCount;
		this.courses = courses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organisation_id", nullable = false)
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "branch_name", nullable = false, length = 200)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "branch_email_id", length = 45)
	public String getBranchEmailId() {
		return this.branchEmailId;
	}

	public void setBranchEmailId(String branchEmailId) {
		this.branchEmailId = branchEmailId;
	}

	@Column(name = "branch_phone_no", nullable = false, length = 45)
	public String getBranchPhoneNo() {
		return this.branchPhoneNo;
	}

	public void setBranchPhoneNo(String branchPhoneNo) {
		this.branchPhoneNo = branchPhoneNo;
	}

	@Column(name = "branch_alternative_phone_no", length = 45)
	public String getBranchAlternativePhoneNo() {
		return this.branchAlternativePhoneNo;
	}

	public void setBranchAlternativePhoneNo(String branchAlternativePhoneNo) {
		this.branchAlternativePhoneNo = branchAlternativePhoneNo;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "created_date", nullable = false, length = 45)
	public String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "branch_code", nullable = false, length = 45)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisationBranch", cascade = CascadeType.ALL)
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "branch_count")
	public Integer getBranchCount() {
		return branchCount;
	}

	public void setBranchCount(Integer branchCount) {
		this.branchCount = branchCount;
	}

}
