package com.rockstudios.domain;
// Generated Aug 19, 2016 1:16:32 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Organisation generated by hbm2java
 */
@Entity
@Table(name = "organisation", catalog = "rockstudios")
public class Organisation implements java.io.Serializable {

	private String id;
	private String organisationName;
	private String status;
	private Date createdDate;
	private Set<OrganisationBranch> organisationBranches = new HashSet<OrganisationBranch>(0);

	public Organisation() {
	}

	public Organisation(String id, String organisationName, String status, Date createdDate) {
		this.id = id;
		this.organisationName = organisationName;
		this.status = status;
		this.createdDate = createdDate;
	}

	public Organisation(String id, String organisationName, String status, Date createdDate,
			Set<OrganisationBranch> organisationBranches) {
		this.id = id;
		this.organisationName = organisationName;
		this.status = status;
		this.createdDate = createdDate;
		this.organisationBranches = organisationBranches;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "organisation_name", nullable = false, length = 200)
	public String getOrganisationName() {
		return this.organisationName;
	}

	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<OrganisationBranch> getOrganisationBranches() {
		return this.organisationBranches;
	}

	public void setOrganisationBranches(Set<OrganisationBranch> organisationBranches) {
		this.organisationBranches = organisationBranches;
	}

}
