package com.rockstudios.domain;
// Generated Aug 19, 2016 1:16:32 PM by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "rockstudios")
public class Payment extends AbstractDomain implements java.io.Serializable {

	private Users users;
	private CourseProgramBatchStudent courseProgramBatchStudent;
	private BigDecimal payableAmount;
	private BigDecimal paidAmount;
	private BigDecimal dueAmount;
	private Date paymentDate;
	private Date createdDate;
	private String status;
	private String comments;

	public Payment() {
	}

	public Payment(String id, Users users, CourseProgramBatchStudent courseProgramBatchStudent,
			BigDecimal payableAmount, BigDecimal paidAmount, BigDecimal dueAmount, Date paymentDate, Date createdDate,
			String status) {
		this.id = id;
		this.users = users;
		this.courseProgramBatchStudent = courseProgramBatchStudent;
		this.payableAmount = payableAmount;
		this.paidAmount = paidAmount;
		this.dueAmount = dueAmount;
		this.paymentDate = paymentDate;
		this.createdDate = createdDate;
		this.status = status;
	}

	public Payment(String id, Users users, CourseProgramBatchStudent courseProgramBatchStudent,
			BigDecimal payableAmount, BigDecimal paidAmount, BigDecimal dueAmount, Date paymentDate, Date createdDate,
			String status, String comments) {
		this.id = id;
		this.users = users;
		this.courseProgramBatchStudent = courseProgramBatchStudent;
		this.payableAmount = payableAmount;
		this.paidAmount = paidAmount;
		this.dueAmount = dueAmount;
		this.paymentDate = paymentDate;
		this.createdDate = createdDate;
		this.status = status;
		this.comments = comments;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_program_batch_student_id", nullable = false)
	public CourseProgramBatchStudent getCourseProgramBatchStudent() {
		return this.courseProgramBatchStudent;
	}

	public void setCourseProgramBatchStudent(CourseProgramBatchStudent courseProgramBatchStudent) {
		this.courseProgramBatchStudent = courseProgramBatchStudent;
	}

	@Column(name = "payable_amount", nullable = false, precision = 7)
	public BigDecimal getPayableAmount() {
		return this.payableAmount;
	}

	public void setPayableAmount(BigDecimal payableAmount) {
		this.payableAmount = payableAmount;
	}

	@Column(name = "paid_amount", nullable = false, precision = 7)
	public BigDecimal getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(BigDecimal paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Column(name = "due_amount", nullable = false, precision = 7)
	public BigDecimal getDueAmount() {
		return this.dueAmount;
	}

	public void setDueAmount(BigDecimal dueAmount) {
		this.dueAmount = dueAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_date", nullable = false, length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "comments", length = 1000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
