package com.rockstudios.domain;
// Generated Aug 19, 2016 1:16:32 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "program", catalog = "rockstudios")
public class Program implements java.io.Serializable {

	private String id;
	private String programName;
	private String duration;
	private String status;
	private String description;
	private Set<CourseProgram> coursePrograms = new HashSet<CourseProgram>(0);

	public Program() {
	}

	public Program(String id, String programName, String duration, String status) {
		this.id = id;
		this.programName = programName;
		this.duration = duration;
		this.status = status;
	}

	public Program(String id, String programName, String duration, String status, String description,
			Set<CourseProgram> coursePrograms) {
		this.id = id;
		this.programName = programName;
		this.duration = duration;
		this.status = status;
		this.description = description;
		this.coursePrograms = coursePrograms;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "program_name", nullable = false, length = 45)
	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@Column(name = "duration", nullable = false, length = 45)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "program")
	public Set<CourseProgram> getCoursePrograms() {
		return this.coursePrograms;
	}

	public void setCoursePrograms(Set<CourseProgram> coursePrograms) {
		this.coursePrograms = coursePrograms;
	}

}
